# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install black flake8 pytest

      - name: Black formatting check
        run: black --check .

      - name: flake8 lint
        run: flake8 .

      - name: Run pytest
        run: pytest -q
